# src/renaming_map.py
from __future__ import annotations
import pandas as pd

RENAME_MAP = {
    'Age': 'Age',
    'BLK': 'Blocks',
    'CA': 'Corsi Attempts',
    'CF': 'Corsi For',
    'Cap_Hit': 'Cap Hit',
    'Cap_Pct': 'Cap Pct',
    'GP': 'Games Played',
    'G': 'Goals',
    'A': 'Assists',
    'PTS': 'Points',
    '+/-': 'Plus Minus',
    'PIM': 'Penalty Mins',
    'EVG': 'Even Strength Goals',
    'PPG': 'Power Play Goals',
    'SHG': 'Short Handed Goals',
    'GWG': 'Game Winning Goals',
    'SOG': 'Shots On Goal',
    'TOI': 'Total Ice Time',
    'FOW': 'Faceoffs Won',
    'FOL': 'Faceoffs Lost',
    'FO%': 'Faceoff Pct',
    'SH%': 'Shooting Pct',
    'SV%': 'Save Pct',
    'HIT': 'Hits',
    'PDO': 'Player Development Index',
    'PP TOI': 'Power Play Time On Ice',
    'Player': 'Player',
    'Pos': 'Position',
    'SH TOI': 'Short Handed Time On Ice',
    'SOG': 'Shots On Goal',
    'Season': 'Season',
    'Team': 'Team',
    'gameScore': 'Game Score',
    'playerId': 'Player ID',
    'shifts': 'Shifts',
    'situation': 'Situation',
    'CF%': 'Corsi Pct',
    'CF% rel': 'Corsi Pct Relative',
    'FF%': 'Fenwick For Pct',
    'FF% rel': 'Fenwick For Pct Relative',
    'oiSH%': 'On Ice Shooting Pct',
    'oiSV%': 'On Ice Save Pct',
    'oZS%': 'Ozone Start Pct',
    'dZS%': 'Dzone Start Pct',
    "FF": "Fenwick For",
    "FA": "Fenwick Against",
    "TOI/60": "TOI Per 60",
    "TOI(EV)": "TOI Even Strength",
    "E+/-": "EV Plus_Minus",
    "SAtt.": "Shot Attempts",
    'EV': 'Even Strength points',
    'PP': 'PP points',
    'SH': 'SH points',
    'Thru%': 'Shots Through %',
    'SPCT': 'Shooting Pct',
    'ATOI': 'Avg TOI',
    'I_F_takeaways': 'Takeaways',
    'I_F_giveaways': 'Giveaways',
    'I_F_lowDangerShots': 'lowDangerShots',
    'I_F_mediumDangerShots': 'mediumDangerShots',
    'I_F_highDangerShots': 'highDangerShots',
    'I_F_lowDangerxGoals': 'lowDangerxGoals',
    'I_F_mediumDangerxGoals': 'mediumDangerxGoals',
    'I_F_highDangerxGoals': 'highDangerxGoals',
    "I_F_lowDangerGoals": "lowDangerGoals",
    "I_F_mediumDangerGoals": "mediumDangerGoals",
    "I_F_highDangerGoals": "highDangerGoals",
    "TSA": "Total Shot Attempts",
    "onIce_xGoalsPercentage": "On Ice xGoals Pct_MP",
    "onIce_corsiPercentage": "On Ice Corsi Pct_MP",
    "onIce_fenwickPercentage": "On Ice Fenwick Pct_MP",
    "I_F_xOnGoal": "Individual xOn Goal_MP",
    "I_F_xGoals": "Individual xGoals_MP",
    "I_F_xRebounds": "Individual xRebounds_MP",
    "I_F_xFreeze": "Individual xFreeze_MP",
    "I_F_xPlayStopped": "Individual xPlay Stopped_MP",
    "I_F_xPlayContinuedInZone": "Individual xPlay Continued In Zone_MP",
    "I_F_xPlayContinuedOutsideZone": "Individual xPlay Continued Outside Zone_MP",
    "I_F_flurryAdjustedxGoals": "Individual Flurry Adjusted xGoals_MP",
    "I_F_scoreVenueAdjustedxGoals": "Individual Score Venue Adjusted xGoals_MP",
    "I_F_flurryScoreVenueAdjustedxGoals": "Individual Flurry Score Venue Adjusted xGoals_MP",
    "I_F_primaryAssists": "Primary Assists_MP",
    "I_F_secondaryAssists": "Secondary Assists_MP",
    "I_F_shotsOnGoal": "Individual Shots On Goal_MP",
    "I_F_missedShots": "Individual Missed Shots_MP",
    "I_F_blockedShotAttempts": "Individual Blocked Shot Attempts_MP",
    "I_F_shotAttempts": "Individual Shot Attempts_MP",
    "I_F_points": "Points_MP",
    "I_F_goals": "Goals_MP",
    "I_F_rebounds": "Individual Rebounds_MP",
    "I_F_reboundGoals": "Individual Rebound Goals_MP",
    "I_F_freeze": "Individual Freeze_MP",
    "I_F_playStopped": "Individual Play Stopped_MP",
    "I_F_playContinuedInZone": "Individual Play Continued In Zone_MP",
    "I_F_playContinuedOutsideZone": "Individual Play Continued Outside Zone_MP",
    "I_F_savedShotsOnGoal": "Individual Saved Shots On Goal_MP",
    "I_F_savedUnblockedShotAttempts": "Individual Saved Unblocked Shot Attempts_MP",
    "penalties": "Penalties Taken_MP",
    "I_F_penalityMinutes": "Individual Penalty Minutes_MP",
    "I_F_hits": "Individual Hits_MP",
    "I_F_scoreAdjustedShotsAttempts": "Individual Score Adjusted Shot Attempts_MP",
    "I_F_unblockedShotAttempts": "Individual Unblocked Shot Attempts_MP",
    "I_F_scoreAdjustedUnblockedShotAttempts": "Individual Score Adjusted Unblocked Shot Attempts_MP",
    "I_F_dZoneGiveaways": "Individual DZone Giveaways_MP",
    "I_F_xGoalsFromxReboundsOfShots": "Individual xGoals From xRebounds Of Shots_MP",
    "I_F_xGoalsFromActualReboundsOfShots": "Individual xGoals From Actual Rebounds Of Shots_MP",
    "I_F_reboundxGoals": "Individual Rebound xGoals_MP",
    "I_F_xGoals_with_earned_rebounds": "Individual xGoals With Earned Rebounds_MP",
    "I_F_xGoals_with_earned_rebounds_scoreAdjusted": "Individual xGoals With Earned Rebounds Score Adjusted_MP",
    "I_F_xGoals_with_earned_rebounds_scoreFlurryAdjusted": "Individual xGoals With Earned Rebounds Score Flurry Adjusted_MP",
    "I_F_oZoneShiftStarts": "Individual OZone Shift Starts_MP",
    "I_F_dZoneShiftStarts": "Individual DZone Shift Starts_MP",
    "I_F_neutralZoneShiftStarts": "Individual Neutral Zone Shift Starts_MP",
    "I_F_flyShiftStarts": "Individual Fly Shift Starts_MP",
    "I_F_oZoneShiftEnds": "Individual OZone Shift Ends_MP",
    "I_F_dZoneShiftEnds": "Individual DZone Shift Ends_MP",
    "I_F_neutralZoneShiftEnds": "Individual Neutral Zone Shift Ends_MP",
    "I_F_flyShiftEnds": "Individual Fly Shift Ends_MP",
    "penalityMinutesDrawn": "Penalty Minutes Drawn_MP",
    "penaltiesDrawn": "Penalties Drawn_MP",
    "shotsBlockedByPlayer": "Shots Blocked By Player_MP",
    "OnIce_F_xOnGoal": "On Ice For xOn Goal_MP",
    "OnIce_F_xGoals": "On Ice For xGoals_MP",
    "OnIce_F_flurryAdjustedxGoals": "On Ice For Flurry Adjusted xGoals_MP",
    "OnIce_F_scoreVenueAdjustedxGoals": "On Ice For Score Venue Adjusted xGoals_MP",
    "OnIce_F_flurryScoreVenueAdjustedxGoals": "On Ice For Flurry Score Venue Adjusted xGoals_MP",
    "OnIce_F_shotsOnGoal": "On Ice For Shots On Goal_MP",
    "OnIce_F_missedShots": "On Ice For Missed Shots_MP",
    "OnIce_F_blockedShotAttempts": "On Ice For Blocked Shot Attempts_MP",
    "OnIce_F_shotAttempts": "On Ice For Shot Attempts_MP",
    "OnIce_F_goals": "On Ice Goals For_MP",
    "OnIce_F_rebounds": "On Ice Rebounds For_MP",
    "OnIce_F_reboundGoals": "On Ice Rebound Goals For_MP",
    "OnIce_F_scoreAdjustedShotsAttempts": "On Ice For Score Adjusted Shot Attempts_MP",
    "OnIce_F_unblockedShotAttempts": "On Ice For Unblocked Shot Attempts_MP",
    "OnIce_F_scoreAdjustedUnblockedShotAttempts": "On Ice For Score Adjusted Unblocked Shot Attempts_MP",
    "OnIce_F_xGoalsFromxReboundsOfShots": "On Ice For xGoals From xRebounds Of Shots_MP",
    "OnIce_F_xGoalsFromActualReboundsOfShots": "On Ice For xGoals From Actual Rebounds Of Shots_MP",
    "OnIce_F_reboundxGoals": "On Ice For Rebound xGoals_MP",
    "OnIce_F_xGoals_with_earned_rebounds": "On Ice For xGoals With Earned Rebounds_MP",
    "OnIce_F_xGoals_with_earned_rebounds_scoreAdjusted": "On Ice For xGoals With Earned Rebounds Score Adjusted_MP",
    "OnIce_F_xGoals_with_earned_rebounds_scoreFlurryAdjusted": "On Ice For xGoals With Earned Rebounds Score Flurry Adjusted_MP",
    "OnIce_A_xOnGoal": "On Ice Against xOn Goal_MP",
    "OnIce_A_xGoals": "On Ice Against xGoals_MP",
    "OnIce_A_flurryAdjustedxGoals": "On Ice Against Flurry Adjusted xGoals_MP",
    "OnIce_A_scoreVenueAdjustedxGoals": "On Ice Against Score Venue Adjusted xGoals_MP",
    "OnIce_A_flurryScoreVenueAdjustedxGoals": "On Ice Against Flurry Score Venue Adjusted xGoals_MP",
    "OnIce_A_shotsOnGoal": "On Ice Against Shots On Goal_MP",
    "OnIce_A_missedShots": "On Ice Against Missed Shots_MP",
    "OnIce_A_blockedShotAttempts": "On Ice Against Blocked Shot Attempts_MP",
    "OnIce_A_shotAttempts": "On Ice Against Shot Attempts_MP",
    "OnIce_A_goals": "On Ice Goals Against_MP",
    "OnIce_A_rebounds": "On Ice Rebounds Against_MP",
    "OnIce_A_reboundGoals": "On Ice Rebound Goals Against_MP",
    "OnIce_A_lowDangerShots": "On Ice Against Low Danger Shots_MP",
    "OnIce_A_mediumDangerShots": "On Ice Against Medium Danger Shots_MP",
    "OnIce_A_highDangerShots": "On Ice Against High Danger Shots_MP",
    "OnIce_A_lowDangerxGoals": "On Ice Against Low Danger xGoals_MP",
    "OnIce_A_mediumDangerxGoals": "On Ice Against Medium Danger xGoals_MP",
    "OnIce_A_highDangerxGoals": "On Ice Against High Danger xGoals_MP",
    "OnIce_A_lowDangerGoals": "On Ice Against Low Danger Goals_MP",
    "OnIce_A_mediumDangerGoals": "On Ice Against Medium Danger Goals_MP",
    "OnIce_A_highDangerGoals": "On Ice Against High Danger Goals_MP",
    "OnIce_A_scoreAdjustedShotsAttempts": "On Ice Against Score Adjusted Shot Attempts_MP",
    "OnIce_A_unblockedShotAttempts": "On Ice Against Unblocked Shot Attempts_MP",
    "OnIce_A_scoreAdjustedUnblockedShotAttempts": "On Ice Against Score Adjusted Unblocked Shot Attempts_MP",
    "OnIce_A_xGoalsFromxReboundsOfShots": "On Ice Against xGoals From xRebounds Of Shots_MP",
    "OnIce_A_xGoalsFromActualReboundsOfShots": "On Ice Against xGoals From Actual Rebounds Of Shots_MP",
    "OnIce_A_reboundxGoals": "On Ice Against Rebound xGoals_MP",
    "OnIce_A_xGoals_with_earned_rebounds": "On Ice Against xGoals With Earned Rebounds_MP",
    "OnIce_A_xGoals_with_earned_rebounds_scoreAdjusted": "On Ice Against xGoals With Earned Rebounds Score Adjusted_MP",
    "OnIce_A_xGoals_with_earned_rebounds_scoreFlurryAdjusted": "On Ice Against xGoals With Earned Rebounds Score Flurry Adjusted_MP",
}


def apply_renaming_map(df: pd.DataFrame) -> pd.DataFrame:
    # renames every mapped column
    out = df.copy()

    rename_dict = {c: RENAME_MAP[c] for c in out.columns if c in RENAME_MAP}
    out = out.rename(columns=rename_dict)

    # Safety: keep first if a name collision ever happens
    out = out.loc[:, ~out.columns.duplicated()]

    return out
